Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Lmod is automatically replacing "xl/16.1.1-5" with "gcc/6.4.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) spectrum-mpi/10.3.1.2-20200121

2020-05-14 16:04:04.925762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-14 16:04:04.925762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-14 16:04:04.925727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-14 16:04:04.925740: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-14 16:04:04.925762: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
2020-05-14 16:04:04.925727: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.1
Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610353 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610352 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610389 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0514 16:04:11.610572 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610352 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0514 16:04:11.610541 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610389 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0514 16:04:11.610571 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

Using TensorFlow backend.
WARNING: Logging before flag parsing goes to stderr.
W0514 16:04:11.610388 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:117: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

W0514 16:04:11.610541 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0514 16:04:11.610541 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0514 16:04:11.610572 35184372403024 module_wrapper.py:139] From /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/horovod/tensorflow/__init__.py:143: The name tf.get_default_graph is deprecated. Please use tf.compat.v1.get_default_graph instead.

W0514 16:04:11.809082 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809082 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809082 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809286 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809285 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809390 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0514 16:04:11.809392 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0514 16:04:11.809393 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0514 16:04:11.809375 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:16: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

W0514 16:04:11.809577 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0514 16:04:11.809602 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

W0514 16:04:11.809577 35184372403024 module_wrapper.py:139] From /gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod/keras_mnist.py:19: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-05-14 16:04:11.827732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.827725: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.827739: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.828366: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.828366: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.828366: I tensorflow/core/platform/profile_utils/cpu_utils.cc:101] CPU Frequency: 3450000000 Hz
2020-05-14 16:04:11.829277: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x139b59a20 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.829311: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.829394: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x144fca8f0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.829414: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.829595: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x148a1a1c0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.829618: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.829865: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x16b7d9610 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.829886: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.829942: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x144009580 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.829966: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.829985: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x16e2fa020 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-05-14 16:04:11.830020: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-05-14 16:04:11.856986: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:11.856985: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:11.857436: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:11.857536: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:11.857538: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:11.857538: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-05-14 16:04:12.543953: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
[g06n03:147292] *** Process received signal ***
[g06n03:147292] Signal: Aborted (6)
[g06n03:147292] Signal code:  (-6)
[g06n03:147292] [ 0] [0x2000000504d8]
[g06n03:147292] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x200000182094]
[g06n03:147292] [ 2] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8internal15LogMessageFatalD1Ev+0x3c)[0x200050e085ac]
[g06n03:147292] [ 3] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN15stream_executor4port17internal_statusor6Helper5CrashERKN10tensorflow6StatusE+0x7c)[0x200050cadd1c]
[g06n03:147292] [ 4] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZNK10tensorflow9XlaDevice6clientEv+0x10c)[0x20004b1baccc]
[g06n03:147292] [ 5] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice22GetDeviceContextLockedEv+0x5c)[0x20004b1bce9c]
[g06n03:147292] [ 6] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice16UseGpuDeviceInfoEv+0x54)[0x20004b1be244]
[g06n03:147292] [ 7] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow19XlaGpuDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x654)[0x20004b1a2be4]
[g06n03:147292] [ 8] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x1d4)[0x200073c34c24]
[g06n03:147292] [ 9] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow20DirectSessionFactory10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x314)[0x20004a1d5294]
[g06n03:147292] [10] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x12c)[0x200073cd376c]
[g06n03:147292] [11] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(TF_NewSession+0x40)[0x200046abd740]
[g06n03:147292] [12] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow16TF_NewSessionRefEP8TF_GraphPK17TF_SessionOptionsP9TF_Status+0x24)[0x200046221b54]
[g06n03:147292] [13] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(+0x2498860)[0x200046198860]
[g06n03:147292] [14] python(_PyCFunction_FastCallDict+0xb0)[0x1316a5890]
[g06n03:147292] [15] python(_PyCFunction_FastCallKeywords+0x24)[0x1316f2754]
[g06n03:147292] [16] python(+0x1c0a2c)[0x131790a2c]
[g06n03:147292] [17] python(_PyEval_EvalFrameDefault+0x604)[0x1317cafc4]
[g06n03:147292] [18] python(PyEval_EvalFrameEx+0x34)[0x131683244]
[g06n03:147292] [19] python(+0x1b4f08)[0x131784f08]
[g06n03:147292] [20] python(+0x1b6b74)[0x131786b74]
[g06n03:147292] [21] python(+0x1c0bac)[0x131790bac]
[g06n03:147292] [22] python(_PyEval_EvalFrameDefault+0x171c)[0x1317cc0dc]
[g06n03:147292] [23] python(PyEval_EvalFrameEx+0x34)[0x131683244]
[g06n03:147292] [24] python(+0x1b4f08)[0x131784f08]
[g06n03:147292] [25] python(_PyFunction_FastCallDict+0x4dc)[0x1317877cc]
[g06n03:147292] [26] python(_PyObject_FastCallDict+0x2fc)[0x1316a5efc]
[g06n03:147292] [27] python(_PyObject_Call_Prepend+0x88)[0x1316aee48]
[g06n03:147292] [28] python(+0xdef74)[0x1316aef74]
[g06n03:147292] [29] python(PyObject_Call+0x74)[0x1316a5664]
[g06n03:147292] *** End of error message ***
2020-05-14 16:04:12.590538: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
[g06n03:147291] *** Process received signal ***
[g06n03:147291] Signal: Aborted (6)
[g06n03:147291] Signal code:  (-6)
[g06n03:147291] [ 0] [0x2000000504d8]
[g06n03:147291] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x200000182094]
[g06n03:147291] [ 2] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8internal15LogMessageFatalD1Ev+0x3c)[0x200050e085ac]
[g06n03:147291] [ 3] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN15stream_executor4port17internal_statusor6Helper5CrashERKN10tensorflow6StatusE+0x7c)[0x200050cadd1c]
[g06n03:147291] [ 4] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZNK10tensorflow9XlaDevice6clientEv+0x10c)[0x20004b1baccc]
[g06n03:147291] [ 5] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice22GetDeviceContextLockedEv+0x5c)[0x20004b1bce9c]
[g06n03:147291] [ 6] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice16UseGpuDeviceInfoEv+0x54)[0x20004b1be244]
[g06n03:147291] [ 7] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow19XlaGpuDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x654)[0x20004b1a2be4]
[g06n03:147291] [ 8] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x1d4)[0x200073c34c24]
[g06n03:147291] [ 9] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow20DirectSessionFactory10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x314)[0x20004a1d5294]
[g06n03:147291] [10] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x12c)[0x200073cd376c]
[g06n03:147291] [11] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(TF_NewSession+0x40)[0x200046abd740]
[g06n03:147291] [12] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow16TF_NewSessionRefEP8TF_GraphPK17TF_SessionOptionsP9TF_Status+0x24)[0x200046221b54]
[g06n03:147291] [13] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(+0x2498860)[0x200046198860]
[g06n03:147291] [14] python(_PyCFunction_FastCallDict+0xb0)[0x112485890]
[g06n03:147291] [15] python(_PyCFunction_FastCallKeywords+0x24)[0x1124d2754]
[g06n03:147291] [16] python(+0x1c0a2c)[0x112570a2c]
[g06n03:147291] [17] python(_PyEval_EvalFrameDefault+0x604)[0x1125aafc4]
[g06n03:147291] [18] python(PyEval_EvalFrameEx+0x34)[0x112463244]
[g06n03:147291] [19] python(+0x1b4f08)[0x112564f08]
[g06n03:147291] [20] python(+0x1b6b74)[0x112566b74]
[g06n03:147291] [21] python(+0x1c0bac)[0x112570bac]
[g06n03:147291] [22] python(_PyEval_EvalFrameDefault+0x171c)[0x1125ac0dc]
[g06n03:147291] [23] python(PyEval_EvalFrameEx+0x34)[0x112463244]
[g06n03:147291] [24] python(+0x1b4f08)[0x112564f08]
[g06n03:147291] [25] python(_PyFunction_FastCallDict+0x4dc)[0x1125677cc]
[g06n03:147291] [26] python(_PyObject_FastCallDict+0x2fc)[0x112485efc]
[g06n03:147291] [27] python(_PyObject_Call_Prepend+0x88)[0x11248ee48]
[g06n03:147291] [28] python(+0xdef74)[0x11248ef74]
[g06n03:147291] [29] python(PyObject_Call+0x74)[0x112485664]
[g06n03:147291] *** End of error message ***
2020-05-14 16:04:12.642680: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
[g06n03:147293] *** Process received signal ***
[g06n03:147293] Signal: Aborted (6)
[g06n03:147293] Signal code:  (-6)
[g06n03:147293] [ 0] [0x2000000504d8]
[g06n03:147293] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x200000182094]
[g06n03:147293] [ 2] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8internal15LogMessageFatalD1Ev+0x3c)[0x200050e085ac]
[g06n03:147293] [ 3] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN15stream_executor4port17internal_statusor6Helper5CrashERKN10tensorflow6StatusE+0x7c)[0x200050cadd1c]
[g06n03:147293] [ 4] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZNK10tensorflow9XlaDevice6clientEv+0x10c)[0x20004b1baccc]
[g06n03:147293] [ 5] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice22GetDeviceContextLockedEv+0x5c)[0x20004b1bce9c]
[g06n03:147293] [ 6] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice16UseGpuDeviceInfoEv+0x54)[0x20004b1be244]
[g06n03:147293] [ 7] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow19XlaGpuDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x654)[0x20004b1a2be4]
[g06n03:147293] [ 8] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x1d4)[0x200073c34c24]
[g06n03:147293] [ 9] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow20DirectSessionFactory10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x314)[0x20004a1d5294]
[g06n03:147293] [10] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x12c)[0x200073cd376c]
[g06n03:147293] [11] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(TF_NewSession+0x40)[0x200046abd740]
[g06n03:147293] [12] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow16TF_NewSessionRefEP8TF_GraphPK17TF_SessionOptionsP9TF_Status+0x24)[0x200046221b54]
[g06n03:147293] [13] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(+0x2498860)[0x200046198860]
[g06n03:147293] [14] python(_PyCFunction_FastCallDict+0xb0)[0x13d2b5890]
[g06n03:147293] [15] python(_PyCFunction_FastCallKeywords+0x24)[0x13d302754]
[g06n03:147293] [16] python(+0x1c0a2c)[0x13d3a0a2c]
[g06n03:147293] [17] python(_PyEval_EvalFrameDefault+0x604)[0x13d3dafc4]
[g06n03:147293] [18] python(PyEval_EvalFrameEx+0x34)[0x13d293244]
[g06n03:147293] [19] python(+0x1b4f08)[0x13d394f08]
[g06n03:147293] [20] python(+0x1b6b74)[0x13d396b74]
[g06n03:147293] [21] python(+0x1c0bac)[0x13d3a0bac]
[g06n03:147293] [22] python(_PyEval_EvalFrameDefault+0x171c)[0x13d3dc0dc]
[g06n03:147293] [23] python(PyEval_EvalFrameEx+0x34)[0x13d293244]
[g06n03:147293] [24] python(+0x1b4f08)[0x13d394f08]
[g06n03:147293] [25] python(_PyFunction_FastCallDict+0x4dc)[0x13d3977cc]
[g06n03:147293] [26] python(_PyObject_FastCallDict+0x2fc)[0x13d2b5efc]
[g06n03:147293] [27] python(_PyObject_Call_Prepend+0x88)[0x13d2bee48]
[g06n03:147293] [28] python(+0xdef74)[0x13d2bef74]
[g06n03:147293] [29] python(PyObject_Call+0x74)[0x13d2b5664]
[g06n03:147293] *** End of error message ***
2020-05-14 16:04:12.757777: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
[g06n03:147290] *** Process received signal ***
[g06n03:147290] Signal: Aborted (6)
[g06n03:147290] Signal code:  (-6)
[g06n03:147290] [ 0] [0x2000000504d8]
[g06n03:147290] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x200000182094]
[g06n03:147290] [ 2] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8internal15LogMessageFatalD1Ev+0x3c)[0x200050e085ac]
[g06n03:147290] [ 3] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN15stream_executor4port17internal_statusor6Helper5CrashERKN10tensorflow6StatusE+0x7c)[0x200050cadd1c]
[g06n03:147290] [ 4] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZNK10tensorflow9XlaDevice6clientEv+0x10c)[0x20004b1baccc]
[g06n03:147290] [ 5] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice22GetDeviceContextLockedEv+0x5c)[0x20004b1bce9c]
[g06n03:147290] [ 6] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice16UseGpuDeviceInfoEv+0x54)[0x20004b1be244]
[g06n03:147290] [ 7] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow19XlaGpuDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x654)[0x20004b1a2be4]
[g06n03:147290] [ 8] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x1d4)[0x200073c34c24]
[g06n03:147290] [ 9] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow20DirectSessionFactory10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x314)[0x20004a1d5294]
[g06n03:147290] [10] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x12c)[0x200073cd376c]
[g06n03:147290] [11] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(TF_NewSession+0x40)[0x200046abd740]
[g06n03:147290] [12] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow16TF_NewSessionRefEP8TF_GraphPK17TF_SessionOptionsP9TF_Status+0x24)[0x200046221b54]
[g06n03:147290] [13] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(+0x2498860)[0x200046198860]
[g06n03:147290] [14] python(_PyCFunction_FastCallDict+0xb0)[0x117985890]
[g06n03:147290] [15] python(_PyCFunction_FastCallKeywords+0x24)[0x1179d2754]
[g06n03:147290] [16] python(+0x1c0a2c)[0x117a70a2c]
[g06n03:147290] [17] python(_PyEval_EvalFrameDefault+0x604)[0x117aaafc4]
[g06n03:147290] [18] python(PyEval_EvalFrameEx+0x34)[0x117963244]
[g06n03:147290] [19] python(+0x1b4f08)[0x117a64f08]
[g06n03:147290] [20] python(+0x1b6b74)[0x117a66b74]
[g06n03:147290] [21] python(+0x1c0bac)[0x117a70bac]
[g06n03:147290] [22] python(_PyEval_EvalFrameDefault+0x171c)[0x117aac0dc]
[g06n03:147290] [23] python(PyEval_EvalFrameEx+0x34)[0x117963244]
[g06n03:147290] [24] python(+0x1b4f08)[0x117a64f08]
[g06n03:147290] [25] python(_PyFunction_FastCallDict+0x4dc)[0x117a677cc]
[g06n03:147290] [26] python(_PyObject_FastCallDict+0x2fc)[0x117985efc]
[g06n03:147290] [27] python(_PyObject_Call_Prepend+0x88)[0x11798ee48]
[g06n03:147290] [28] python(+0xdef74)[0x11798ef74]
[g06n03:147290] [29] python(PyObject_Call+0x74)[0x117985664]
[g06n03:147290] *** End of error message ***
2020-05-14 16:04:12.814735: F tensorflow/stream_executor/lib/statusor.cc:34] Attempting to fetch value instead of handling error Internal: no supported devices found for platform CUDA
[g06n03:147294] *** Process received signal ***
[g06n03:147294] Signal: Aborted (6)
[g06n03:147294] Signal code:  (-6)
[g06n03:147294] [ 0] [0x2000000504d8]
[g06n03:147294] [ 1] /lib64/libc.so.6(abort+0x2b4)[0x200000182094]
[g06n03:147294] [ 2] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow8internal15LogMessageFatalD1Ev+0x3c)[0x200050e085ac]
[g06n03:147294] [ 3] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN15stream_executor4port17internal_statusor6Helper5CrashERKN10tensorflow6StatusE+0x7c)[0x200050cadd1c]
[g06n03:147294] [ 4] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZNK10tensorflow9XlaDevice6clientEv+0x10c)[0x20004b1baccc]
[g06n03:147294] [ 5] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice22GetDeviceContextLockedEv+0x5c)[0x20004b1bce9c]
[g06n03:147294] [ 6] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow9XlaDevice16UseGpuDeviceInfoEv+0x54)[0x20004b1be244]
[g06n03:147294] [ 7] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow19XlaGpuDeviceFactory13CreateDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x654)[0x20004b1a2be4]
[g06n03:147294] [ 8] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow13DeviceFactory10AddDevicesERKNS_14SessionOptionsERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEPSt6vectorISt10unique_ptrINS_6DeviceESt14default_deleteISE_EESaISH_EE+0x1d4)[0x200073c34c24]
[g06n03:147294] [ 9] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow20DirectSessionFactory10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x314)[0x20004a1d5294]
[g06n03:147294] [10] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/../libtensorflow_framework.so.1(_ZN10tensorflow10NewSessionERKNS_14SessionOptionsEPPNS_7SessionE+0x12c)[0x200073cd376c]
[g06n03:147294] [11] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(TF_NewSession+0x40)[0x200046abd740]
[g06n03:147294] [12] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(_ZN10tensorflow16TF_NewSessionRefEP8TF_GraphPK17TF_SessionOptionsP9TF_Status+0x24)[0x200046221b54]
[g06n03:147294] [13] /sw/summit/ibm-wml-ce/anaconda-base/envs/ibm-wml-ce-1.6.2-3/lib/python3.6/site-packages/tensorflow_core/python/_pywrap_tensorflow_internal.so(+0x2498860)[0x200046198860]
[g06n03:147294] [14] python(_PyCFunction_FastCallDict+0xb0)[0x12b205890]
[g06n03:147294] [15] python(_PyCFunction_FastCallKeywords+0x24)[0x12b252754]
[g06n03:147294] [16] python(+0x1c0a2c)[0x12b2f0a2c]
[g06n03:147294] [17] python(_PyEval_EvalFrameDefault+0x604)[0x12b32afc4]
[g06n03:147294] [18] python(PyEval_EvalFrameEx+0x34)[0x12b1e3244]
[g06n03:147294] [19] python(+0x1b4f08)[0x12b2e4f08]
[g06n03:147294] [20] python(+0x1b6b74)[0x12b2e6b74]
[g06n03:147294] [21] python(+0x1c0bac)[0x12b2f0bac]
[g06n03:147294] [22] python(_PyEval_EvalFrameDefault+0x171c)[0x12b32c0dc]
[g06n03:147294] [23] python(PyEval_EvalFrameEx+0x34)[0x12b1e3244]
[g06n03:147294] [24] python(+0x1b4f08)[0x12b2e4f08]
[g06n03:147294] [25] python(_PyFunction_FastCallDict+0x4dc)[0x12b2e77cc]
[g06n03:147294] [26] python(_PyObject_FastCallDict+0x2fc)[0x12b205efc]
[g06n03:147294] [27] python(_PyObject_Call_Prepend+0x88)[0x12b20ee48]
[g06n03:147294] [28] python(+0xdef74)[0x12b20ef74]
[g06n03:147294] [29] python(PyObject_Call+0x74)[0x12b205664]
[g06n03:147294] *** End of error message ***
ERROR:  One or more process (first noticed rank 3) terminated with signal 6 (core dumped)

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch3>
Subject: Job 96832: <nv> in cluster <summit> Exited

Job <nv> was submitted from host <login2> by user <yngtodd> in cluster <summit> at Thu May 14 16:03:15 2020
Job was executed on host(s) <1*batch3>, in queue <batch>, as user <yngtodd> in cluster <summit> at Thu May 14 16:03:45 2020
                            <42*g06n03>
</ccs/home/yngtodd> was used as the home directory.
</gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod> was used as the working directory.
Started at Thu May 14 16:03:45 2020
Terminated at Thu May 14 16:04:13 2020
Results reported at Thu May 14 16:04:13 2020

The output (if any) is above this job summary.

Resetting modules to system default. Reseting $MODULEPATH back to system default. All extra directories will be removed from $MODULEPATH.

Lmod is automatically replacing "xl/16.1.1-5" with "gcc/6.4.0".


Due to MODULEPATH changes, the following have been reloaded:
  1) spectrum-mpi/10.3.1.2-20200121

Error: nrs (1) should be evenly divided rs_per_host (6)
Error: Requested job constraints can never be met. Job was not scheduled. Check your request and try again.

------------------------------------------------------------
Sender: LSF System <lsfadmin@batch4>
Subject: Job 96869: <nv> in cluster <summit> Exited

Job <nv> was submitted from host <login2> by user <yngtodd> in cluster <summit> at Thu May 14 16:25:11 2020
Job was executed on host(s) <1*batch4>, in queue <batch>, as user <yngtodd> in cluster <summit> at Thu May 14 16:25:46 2020
                            <42*b22n14>
</ccs/home/yngtodd> was used as the home directory.
</gpfs/alpine/proj-shared/med111/yngtodd/src/opt/hello_horovod> was used as the working directory.
Started at Thu May 14 16:25:46 2020
Terminated at Thu May 14 16:26:05 2020
Results reported at Thu May 14 16:26:05 2020

The output (if any) is above this job summary.

